import os
import sys

print(" Wait ")
print(" Installing Module ")
os.system("sudo apt upgrade && sudo apt update -y")
os.system("sudo apt install unzip ")
os.system("sudo apt install golang -y")
os.system("sudo apt install perl -y")
os.system("sudo apt install python3 -y")
os.system("sudo apt  install python2 -y")
os.system("sudo apt install python3-pip -y")
os.system("sudo apt install nodejs -y")
os.system("sudo apt install npm -y")
os.system("chmod +*")
os.system("npm i cluster")
os.system("npm i requests")
os.system("npm i https-proxy-agent")
os.system("npm i crypto-random-string")
os.system("npm i events")
os.system("npm i fs")
os.system("npm i net")
os.system("npm i set-cookie-parser")
os.system("npm i cloudscraper")
os.system("npm i request")
os.system("npm i hcaptcha-solver")
os.system("npm i randomstring")
os.system("npm i cluster")
os.system("npm i random-useragent")
os.system("npm i cloudflare-bypasser")
os.system("npm i axios")
os.system("npm i fake-useragent")
os.system("pip install reguirements.txt -y")
os.system("pip install pystyle -y")
os.system("pip install colors -y ")
os.system("pip install colorate -y ")
os.system("pip install colorama -y ")
os.system("npm i colorate && npm i colors && npm i pystyle")

print(" Installing Selesai ")